### ISSUE TITLE
Automatic publication @18h

### ISSUE THREAD

**Issue by tassia** [tiagovaz/saskatoon#34]
Scheduled harvests should only be made public @18h, so that users know at what time they should check the calendar.

**Comment by RignonNoel** [comment]
I think we can use the model to do this task.

 1. We create a new method ```is_active()```
 2. We implement the logic of this method (field ```active```=```True``` and control of created datetime)
 3. We refactor the code to use ```is_active()``` instead of ```active``` field

---

We could also create a cron task with [celery](https://pypi.python.org/pypi/django-celery) to update data each day at 18H.

**Comment by RignonNoel** [comment]
@tassia If you're ok i can work on.
